/**
 * Merges travelcities.js + regionalcities.js into a single unified cities.js.
 *
 * Unified schema (camelCase throughout):
 *   { name, lat, lon, point: { x, y, wfo } }
 *
 * Strategy:
 *   - Start with all 114 regional cities (canonical for coordinates).
 *   - Add any travel cities whose name doesn't already exist in the regional set.
 *   - Where a city exists in both files with different coordinates, regional wins
 *     (it is the larger, more-maintained dataset). Conflicts are logged.
 *
 * Run: node datagenerators/merge-cities.mjs
 * Output: server/scripts/data/cities.js
 */

import fs from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

// ── load raw data ─────────────────────────────────────────────────────────────

const travelSrc = fs.readFileSync(path.join(root, 'server/scripts/data/travelcities.js'), 'utf8');
const regionalSrc = fs.readFileSync(path.join(root, 'server/scripts/data/regionalcities.js'), 'utf8');

// `const` vars aren't added to a vm context, so extract the array literal directly
const extractArray = (src) => {
	const match = src.match(/=\s*(\[[\s\S]*\]);?\s*$/);
	if (!match) throw new Error('Could not find array literal in source');
	// eslint-disable-next-line no-new-func
	return new Function(`return ${match[1]}`)();
};

const TravelCities = extractArray(travelSrc);
const RegionalCities = extractArray(regionalSrc);

// Normalize travel entry to unified schema
const normTravel = (e) => ({
	name: e.Name,
	lat: e.Latitude,
	lon: e.Longitude,
	point: e.point,
});

// Regional is already close; just rename `city` → `name`
const normRegional = (e) => ({
	name: e.city,
	lat: e.lat,
	lon: e.lon,
	point: e.point,
});

// ── merge ─────────────────────────────────────────────────────────────────────

const merged = RegionalCities.map(normRegional);
const regionalNames = new Set(merged.map((e) => e.name.toLowerCase()));

let added = 0;
let conflicts = 0;

for (const raw of TravelCities) {
	const t = normTravel(raw);
	const existing = merged.find((e) => e.name.toLowerCase() === t.name.toLowerCase());

	if (!existing) {
		merged.push(t);
		added += 1;
		console.log(`  + Added travel-only city: ${t.name}`);
	} else {
		// check for coordinate conflicts
		const latDiff = Math.abs(existing.lat - t.lat);
		const lonDiff = Math.abs(existing.lon - t.lon);
		if (latDiff > 0.01 || lonDiff > 0.01) {
			console.warn(`  ⚠ Conflict: ${t.name}`);
			console.warn(`      travel:   lat=${t.lat} lon=${t.lon}`);
			console.warn(`      regional: lat=${existing.lat} lon=${existing.lon}  ← kept`);
			conflicts += 1;
		}
	}
}

// sort alphabetically for readability
merged.sort((a, b) => a.name.localeCompare(b.name));

// ── emit ──────────────────────────────────────────────────────────────────────

const lines = merged.map((e) =>
	`\t{\n\t\tname: ${JSON.stringify(e.name)},\n\t\tlat: ${e.lat},\n\t\tlon: ${e.lon},\n\t\tpoint: { x: ${e.point.x}, y: ${e.point.y}, wfo: '${e.point.wfo}' },\n\t}`,
);

const output = `// eslint-disable-next-line no-unused-vars
// Unified city data — generated by datagenerators/merge-cities.mjs
// Schema: { name, lat, lon, point: { x, y, wfo } }
// Do not edit by hand; run merge-cities.mjs to regenerate.
const Cities = [\n${lines.join(',\n')},\n];\n`;

const outPath = path.join(root, 'server/scripts/data/cities.js');
fs.writeFileSync(outPath, output, 'utf8');

console.log(`\nDone. ${merged.length} cities → ${outPath}`);
console.log(`  ${added} travel-only cities added, ${conflicts} coordinate conflicts (regional coords kept).`);
